const COINS_FULLFILLED = 'COINS_FULLFILLED';
const COIN_DETAIL_FULLFILLED = 'COIN_DETAIL_FULLFILLED';
const CLEAR_COIN_STATE = 'CLEAR_COIN_STATE';
export { COINS_FULLFILLED, COIN_DETAIL_FULLFILLED, CLEAR_COIN_STATE };
