const LOGIN_SUCCESS = 'LOGIN';
const SIGN_UP = 'SIGN_IN';
const LOGOUT = 'LOGOUT';
const CLEAR_AUTH = 'CLEAR_AUTH';
const GET_STATE = 'GET_STATE';
const PENDING_TRUE = 'PENDING_TRUE';
const PENDING_FALSE = 'PENDING_FALSE';
const SIGNUP_FAILED = 'SIGNUP_FAILED';
const LOGIN_FAILED = 'LOGIN_FAILED';
export {
  LOGIN_SUCCESS,
  LOGOUT,
  SIGN_UP,
  CLEAR_AUTH,
  GET_STATE,
  PENDING_TRUE,
  PENDING_FALSE,
  SIGNUP_FAILED,
  LOGIN_FAILED
};
