const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const SIGN_UP = 'SIGN_IN';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_FAILED = 'LOGOUT_FAILED';
const CLEAR_AUTH = 'CLEAR_AUTH';
const PENDING_TRUE = 'PENDING_TRUE';
const PENDING_FALSE = 'PENDING_FALSE';
const SIGNUP_FAILED = 'SIGNUP_FAILED';
export {
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT_SUCCESS,
  LOGOUT_FAILED,
  SIGN_UP,
  SIGNUP_FAILED,
  CLEAR_AUTH,
  PENDING_TRUE,
  PENDING_FALSE
};
