const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';
const SIGN_UP = 'SIGN_IN';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_FAILED = 'LOGOUT_FAILED';
const CLEAR_AUTH = 'CLEAR_AUTH';
const PENDING_TRUE = 'PENDING_TRUE';
const PENDING_FALSE = 'PENDING_FALSE';
const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
const PROFILE_CREATE_FAILED = 'PROFILE_CREATE_FAILED';
const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';
const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
const SIGNUP_FAILED = 'SIGNUP_FAILED';

export {
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT_SUCCESS,
  LOGOUT_FAILED,
  SIGN_UP,
  SIGNUP_FAILED,
  CLEAR_AUTH,
  PENDING_TRUE,
  PENDING_FALSE,
  UPDATE_PROFILE_FAILED,
  PROFILE_CREATE_FAILED,
  UPDATE_PROFILE_SUCCESS,
  PROFILE_CREATE_SUCCESS
};
